INSERT INTO task (id, title, description) VALUES (1, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (2, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (3, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (4, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (5, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (6, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (7, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (8, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (9, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (10, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (11, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (12, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (13, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (14, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (15, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (16, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (17, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (18, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (19, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (20, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (21, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (22, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (23, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (24, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (25, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (26, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (27, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (28, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (29, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (30, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (31, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (32, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (33, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (34, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (35, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (36, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (37, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (38, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (39, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (40, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (41, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (42, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (43, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (44, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (45, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (46, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (47, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (48, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (49, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (50, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (51, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (52, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (53, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (54, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (55, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (56, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (57, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (58, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (59, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (60, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (61, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (62, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (63, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (64, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (65, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (66, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (67, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (68, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (69, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (70, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (71, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (72, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (73, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (74, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (75, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (76, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (77, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (78, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (79, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (80, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (81, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (82, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (83, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (84, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (85, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (86, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (87, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (88, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (89, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (90, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (91, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (92, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (93, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (94, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (95, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (96, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (97, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (98, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (99, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (100, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (101, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (102, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (103, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (104, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (105, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (106, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (107, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (108, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (109, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (110, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (111, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (112, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (113, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (114, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (115, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (116, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (117, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (118, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (119, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (120, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (121, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (122, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (123, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (124, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (125, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (126, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (127, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (128, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (129, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (130, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (131, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (132, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (133, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (134, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (135, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (136, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (137, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (138, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (139, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (140, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (141, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (142, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (143, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (144, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (145, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (146, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (147, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (148, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (149, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (150, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (151, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (152, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (153, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (154, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (155, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (156, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (157, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (158, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (159, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (160, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (161, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (162, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (163, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (164, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (165, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (166, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (167, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (168, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (169, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (170, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (171, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (172, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (173, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (174, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (175, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (176, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (177, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (178, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (179, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (180, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (181, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (182, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (183, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (184, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (185, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (186, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (187, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (188, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (189, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (190, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (191, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (192, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (193, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (194, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (195, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (196, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (197, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (198, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (199, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (200, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (201, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (202, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (203, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (204, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (205, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (206, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (207, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (208, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (209, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (210, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (211, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (212, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (213, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (214, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (215, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (216, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (217, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (218, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (219, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (220, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (221, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (222, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (223, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (224, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (225, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (226, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (227, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (228, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (229, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (230, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (231, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (232, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (233, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (234, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (235, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (236, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (237, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (238, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (239, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (240, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (241, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (242, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (243, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (244, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (245, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (246, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (247, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (248, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (249, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (250, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (251, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (252, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (253, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (254, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (255, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (256, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (257, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (258, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (259, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (260, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (261, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (262, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (263, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (264, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (265, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (266, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (267, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (268, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (269, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (270, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (271, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (272, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (273, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (274, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (275, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (276, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (277, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (278, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (279, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (280, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (281, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (282, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (283, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (284, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (285, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (286, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (287, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (288, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (289, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (290, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (291, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (292, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (293, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (294, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (295, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (296, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (297, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (298, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (299, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (300, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (301, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (302, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (303, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (304, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (305, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (306, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (307, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (308, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (309, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (310, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (311, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (312, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (313, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (314, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (315, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (316, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (317, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (318, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (319, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (320, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (321, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (322, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (323, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (324, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (325, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (326, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (327, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (328, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (329, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (330, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (331, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (332, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (333, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (334, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (335, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (336, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (337, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (338, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (339, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (340, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (341, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (342, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (343, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (344, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (345, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (346, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (347, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (348, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (349, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (350, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (351, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (352, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (353, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (354, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (355, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (356, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (357, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (358, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (359, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (360, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (361, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (362, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (363, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (364, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (365, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (366, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (367, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (368, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (369, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (370, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (371, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (372, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (373, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (374, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (375, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (376, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (377, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (378, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (379, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (380, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (381, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (382, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (383, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (384, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (385, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (386, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (387, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (388, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (389, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (390, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (391, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (392, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (393, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (394, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (395, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (396, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (397, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (398, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (399, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (400, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (401, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (402, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (403, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (404, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (405, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (406, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (407, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (408, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (409, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (410, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (411, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (412, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (413, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (414, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (415, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (416, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (417, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (418, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (419, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (420, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (421, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (422, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (423, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (424, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (425, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (426, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (427, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (428, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (429, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (430, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (431, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (432, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (433, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (434, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (435, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (436, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (437, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (438, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (439, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (440, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (441, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (442, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (443, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (444, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (445, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (446, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (447, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (448, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (449, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (450, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (451, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (452, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (453, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (454, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (455, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (456, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (457, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (458, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (459, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (460, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (461, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (462, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (463, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (464, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (465, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (466, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (467, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (468, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (469, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (470, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (471, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (472, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (473, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (474, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (475, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (476, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (477, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (478, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (479, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (480, 'Buy groceries', 'Buy milk, eggs, bread');
INSERT INTO task (id, title, description) VALUES (481, 'Clean the house', 'Vacuum and mop the floors');
INSERT INTO task (id, title, description) VALUES (482, 'Finish project', 'Complete the Spring Boot API implementation');
INSERT INTO task (id, title, description) VALUES (483, 'Pay bills', 'Pay electricity and internet bills');
INSERT INTO task (id, title, description) VALUES (484, 'Workout', 'Go for a 5km run');
INSERT INTO task (id, title, description) VALUES (485, 'Read a book', 'Finish reading the new novel');
INSERT INTO task (id, title, description) VALUES (486, 'Plan a trip', 'Research destinations and book tickets');
INSERT INTO task (id, title, description) VALUES (487, 'Call family', 'Have a long overdue chat');
INSERT INTO task (id, title, description) VALUES (488, 'Cook dinner', 'Try a new recipe');
INSERT INTO task (id, title, description) VALUES (489, 'Organize files', 'Sort documents into folders');
INSERT INTO task (id, title, description) VALUES (490, 'Learn SQL', 'Complete SQL tutorial');
INSERT INTO task (id, title, description) VALUES (491, 'Write a blog post', 'Share thoughts on new tech');
INSERT INTO task (id, title, description) VALUES (492, 'Practice guitar', 'Learn a new chord progression');
INSERT INTO task (id, title, description) VALUES (493, 'Meditate', 'Relax and clear your mind');
INSERT INTO task (id, title, description) VALUES (494, 'Water the plants', 'Ensure all plants are healthy');
INSERT INTO task (id, title, description) VALUES (495, 'Fix the car', 'Change oil and check tires');
INSERT INTO task (id, title, description) VALUES (496, 'Update software', 'Install latest updates');
INSERT INTO task (id, title, description) VALUES (497, 'Review budget', 'Analyze expenses and savings');
INSERT INTO task (id, title, description) VALUES (498, 'Schedule a meeting', 'Plan and confirm agenda');
INSERT INTO task (id, title, description) VALUES (499, 'Study for exams', 'Review notes and practice problems');
INSERT INTO task (id, title, description) VALUES (500, 'Buy groceries', 'Buy milk, eggs, bread');
